basePath: /api/v3
host: 127.0.0.1
info:
  contact:
    email: dimapermyakov55@gmai.com
    name: API Support
    url: https://github.com/mightyK1ngRichard
  description: Viking's hikes
  license:
    name: AS IS (NO WARRANTY)
  title: VIKINGS
  version: "1.0"
paths: {}
schemes:
- http
swagger: "2.0"
