basePath: /api/v3
definitions:
  ds.City:
    properties:
      city_name:
        type: string
      description:
        type: string
      id:
        type: integer
      image_url:
        type: string
      status:
        $ref: '#/definitions/ds.CityStatus'
      status_id:
        type: integer
    type: object
  ds.CityStatus:
    properties:
      id:
        type: integer
      statusName:
        type: string
    type: object
host: 127.0.0.1
info:
  contact:
    email: dimapermyakov55@gmai.com
    name: API Support
    url: https://github.com/mightyK1ngRichard
  description: Viking's hikes
  license:
    name: AS IS (NO WARRANTY)
  title: VIKINGS
  version: "1.0"
paths:
  /cities:
    get:
      description: Get a list of cities with optional filtering by city name.
      parameters:
      - description: City name for filtering
        in: query
        name: city
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/ds.City'
            type: array
      summary: Get a list of cities
      tags:
      - cities
schemes:
- http
swagger: "2.0"
